CREATE TABLE IF NOT EXISTS chat_group (
    id BIGSERIAL PRIMARY KEY,
    jid VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
